# Generated by Django 5.0.14 on 2026-03-29 00:59

import django.db.models.deletion
import encrypted_model_fields.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserVerification',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('requires_action', 'Requires Action')], default='not_started', max_length=20)),
                ('stripe_session_id', models.CharField(blank=True, max_length=200, null=True)),
                ('legal_first_name', encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True)),
                ('legal_last_name', encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True)),
                ('id_document_number', encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
