# Generated by Django 5.0.14 on 2026-03-29 19:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_days', models.PositiveSmallIntegerField()),
                ('rental_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commission_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_charged', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deposit_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending_payment', 'Pending Payment'), ('payment_failed', 'Payment Failed'), ('confirmed', 'Confirmed & Paid'), ('active', 'Active (Picked Up)'), ('return_pending', 'Return Initiated'), ('completed', 'Completed (Returned)'), ('disputed', 'Disputed'), ('deposit_released', 'Deposit Released'), ('no_return', 'No-Return Reported'), ('cancelled', 'Cancelled')], default='pending_payment', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pickup_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('return_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('deposit_released_at', models.DateTimeField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='listings.item')),
                ('lender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings_as_lender', to=settings.AUTH_USER_MODEL)),
                ('renter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings_as_renter', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BookingStatusLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('old_status', models.CharField(max_length=30)),
                ('new_status', models.CharField(max_length=30)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='bookings.booking')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HandoverAgreement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pickup_agreed_datetime', models.DateTimeField(blank=True, null=True)),
                ('pickup_location_text', models.CharField(blank=True, max_length=500)),
                ('return_agreed_datetime', models.DateTimeField(blank=True, null=True)),
                ('return_location_text', models.CharField(blank=True, max_length=500)),
                ('pickup_confirmed_renter', models.BooleanField(default=False)),
                ('pickup_confirmed_lender', models.BooleanField(default=False)),
                ('return_confirmed_renter', models.BooleanField(default=False)),
                ('return_confirmed_lender', models.BooleanField(default=False)),
                ('is_pickup_finalized', models.BooleanField(default=False)),
                ('is_return_finalized', models.BooleanField(default=False)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bookings.booking')),
                ('proposed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NoReturnReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_contact_attempt_at', models.DateTimeField()),
                ('description', models.TextField()),
                ('status', models.CharField(default='filed', max_length=30)),
                ('admin_notes', models.TextField(blank=True)),
                ('identity_accessed', models.BooleanField(default=False)),
                ('law_enforcement_ref', models.CharField(blank=True, max_length=200)),
                ('filed_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='bookings.booking')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
